@fId=1
@pId=1

### Test de la route all freelances
GET http://localhost:8000/v1/freelances
Content-Type: application/json

### Test de la création d'un freelance
POST http://localhost:8000/v1/freelances/create
Content-Type: application/json

{
    "nom": "Duflot",
    "email": "jeremy.duflot@example.com",
    "skills": ["JavaScript", "TypeScript", "Node.js"],
    "tjm": 450
}

### Test recherche de freelances par ID
GET http://localhost:8000/v1/freelances/{{fId}}

### Test recherche de projets par skills du freelance
GET http://localhost:8000/v1/freelances/{{fId}}/projets-compatibles

### Test de la candidature à un projet
POST http://localhost:8000/v1/freelances/{{fId}}/postuler/{{pId}}